# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

deploy.skip_cleanup: true

os:
  - linux

sudo: true
services: docker

before_install:
  - "docker pull ubuntu:20.04"
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable -y
  - sudo apt-get --yes --force-yes update -qq
  - sudo apt-get install libgdal-dev libgeos-dev libproj-dev libudunits2-dev libv8-dev libprotobuf-dev protobuf-compiler libjq-dev
  - echo "options(repos = c(CRAN = 'https://packagemanager.rstudio.com/all/__linux__/focal/latest'))" >> ~/.Rprofile.site
  - echo "options(HTTPUserAgent = paste0('R/', getRversion(), ' R (',
       paste(getRversion(), R.version['platform'], R.version['arch'], R.version['os']),
       ')'))" >> ~/.Rprofile.site

language: r
r:
  - release
  - devel
  - oldrel

repos:
  CRAN: https://cran.rstudio.com
  
cache: packages
  
r_packages:
  - sf
  - rgdal
  - rgeos

r_github_packages:
  - r-lib/covr

warnings_are_errors: false

latex: true
pandoc: true

notifications:
  email:
    on_success: never
    on_failure: never

after_success:
      - travis_wait 30 Rscript -e 'covr::codecov()'

#addons:
#  apt_packages:
#      - libgdal-dev
#      - libproj-dev
#      - libgeos-dev
#      - libudunits2-dev
#      - gdal-bin
