# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

deploy.skip_cleanup: true
  
os:
  - linux

dist:
  - bionic

sudo: true

before_install:
  - sudo add-apt-repository ppa:ubuntugis/ubuntugis-unstable
  - sudo apt-get update
  - sudo apt-get install libudunits2-dev libgdal-dev libgeos-dev libproj-dev
  - sudo apt-get install r-cran-rcppeigen r-cran-sf

language: r
r:
  - release
  - devel
  - oldrel

repos:
  CRAN: https://cran.rstudio.com
  
cache: packages
  
r_packages:
  - rgdal
  - rgeos
  - Matrix
  - TMB

r_github_packages:
  - r-lib/covr

warnings_are_errors: false

latex: true
pandoc: true

notifications:
  email:
    on_success: never
    on_failure: never

after_success:
      - travis_wait 30 Rscript -e 'covr::codecov()'